# Generated by Django 4.2.4 on 2023-08-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='address',
            field=models.CharField(help_text='Enter address of customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='city',
            field=models.CharField(help_text='Enter the city of address', max_length=30),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='first_name',
            field=models.CharField(help_text='Enter first name of customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='last_name',
            field=models.CharField(help_text='Enter last name of customer', max_length=30),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington DC'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], help_text='Enter state of address', max_length=25),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='zip_code',
            field=models.CharField(help_text='Enter the zip code address', max_length=10),
        ),
    ]
